Kependudukan/info/urls.py
from django.urls import path
from . import views

urlpatterns  = [
    
]

Kependudukan/kependudukan/urls.py
from django.contrib import admin
from django.urls import path, include

from django.shortcuts import render

def index(rq):
    return render(rq, 'index.html')

def cont(rq):
    return render(rq, 'contact.html')

urlpatterns = [
    path('', index),
    path('cont/', cont),
    
    path('info/', include('info.urls')),
    path('market/', include('market.urls')),
    path('suket/', include('suket.urls')),
    path('admin/', admin.site.urls),
]

Kependudukan/market/urls.py
from django.urls import path
from . import views

urlpatterns  = [
    
]

Kependudukan/suket/urls.py
from django.urls import path
from . import views

urlpatterns  = [
    path('borang', views.borang_isian),
    path('konfirmasi', views.konfirmasi_borang),
    path('daftar', views.daftar_borang),
    path('hapus/<int:id>', views.hapus_borang),
    path('pdf/<int:id>', views.html_to_pdf),
]

Kependudukan/info/models.py
from django.db import models

# Create your models here.

Kependudukan/market/models.py
from django.db import models

# Create your models here.

Kependudukan/suket/models.py
from django.db import models

class Borang(models.Model):
    nama = models.CharField(max_length=20)
    nik = models.CharField(max_length=20)
    alamat = models.CharField(max_length=30)
    no_telpon = models.CharField(max_length=13)
    email = models.EmailField(max_length=20)
    jenis_surat = models.CharField(
        max_length=40, choices=[
        (None, "Jenis Surat"),    
        ('Keluhan', "Keluhan"),
        ('Daftar KTP', "Pendafataran KTP"),
        ('Legalisir', "Legalisir"),
        ('KTM', "Keterangan Tidak Mampu"),
    ], default=None)
    keterangan_tambahan = models.TextField(default="Surat ini diajukan untuk keperluan ...... yang membutuhkan surat pengantar dari pihak kelurahan mohon kiranya pengajuan saya dapat diterima.")

Kependudukan/suket/forms.py
from django import forms
from django.forms import ModelForm
from .models import Borang

# membuat form dari model yang sudah ada di models.py dan terhubung dengan postgresql
# melalui settings.py
class Borang_form(forms.ModelForm):
    class Meta:
        exclude = []
        model = Borang

Kependudukan/info/views.py
from django.shortcuts import render

# Create your views here.

Kependudukan/market/views.py
from django.shortcuts import render

# Create your views here.

Kependudukan/suket/views.py
from django.shortcuts import redirect, render
from .models import Borang
from .forms import Borang_form

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, HttpRequest
from django.template.loader import render_to_string

from weasyprint import HTML
import pdfkit
import datetime


def borang_isian(request):
    form = Borang_form()
    return render(request, 'borang.html', { 'form': form })
    

def daftar_borang(request):
    data = Borang.objects.all()
    return render(request, 'daftar_borang_masuk.html', { 'data': data })

def hapus_borang(request, id):
    Borang.objects.get(id=id).delete()
    return redirect('/suket/daftar')

def html_to_pdf(request, id):
    data = Borang.objects.get(id=id)
    #Belum berhasil langsung konvert ke pdf

    #url = str(request.build_absolute_uri())
    #print(url)
    #pdfkit.from_url(url, 'doc.pdf')
    return render(request, 'pdf.html', { 'data': data })

    """
    data = Borang.objects.get(id=id)
    html_string = render_to_string('pdf.html', { 'data': data, 'date': datetime.date.today(), 'month': datetime.date.today().strftime("%B") })

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/document.pdf')    

    fs = FileSystemStorage('/tmp')
    with fs.open('document.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="document.pdf"'
        return response
    """
    


def konfirmasi_borang(request):
    if request.POST:
        form = Borang_form(request.POST)
        if form.is_valid():
            form.save()
        else :
            #dibuat jangan sampai harus isi lagi
            return redirect('/suket/borang')
        return render(request, 'konfirmasi.html', {'form': form.instance, 'date': datetime.date.today(), 'month': datetime.date.today().strftime("%B")})
        # ini kalau front end nya langsung oleh django, jika menggunakan frontend lain (e.g vue.js)
        # yang diberikan harus data json, bukan instance dari model
    return redirect('/suket/borang')

Kependudukan/suket/templates/borang.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Import bootstrap cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> 
  
    <!-- Import jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"> </script>  
    <script src= "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity= "sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"> </script> 

    <title>Form Isian</title>

</head>
<body>
    <div class="container mt-2">
        <h3>Silakan isi data & keperluan anda</h3>
        <form action="konfirmasi" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <!-- trigger untuk validasi ulang data-->
            <button id="simpan" type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal">
                Simpan
            </button>
            
            <!-- Modal validasi  -->
            <div id="myModal" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" >
                    <!-- konten modal-->
                    <div class="modal-content">
                        <!-- heading modal -->
                        <div class="modal-header" style="background: rgb(36, 150, 62);; color: white;">
                            <h3 class="modal-title" >Validasi</h3>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <!-- body modal -->
                        <div class="modal-body">
                            <p>Anda yakin data sudah benar?</p>
                            <!-- pass data ke display body modal -->
                            <p id="modal_body"></p> 
                        </div>
                        <!-- footer modal -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Konfirmasi</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Modal -->
        </form>
    </div>

    <script type="text/javascript"> 
        $("#simpan").click(function () { 
            var nama = $("#id_nama").val(); 
            var nik = $("#id_nik").val();
            var alamat = $("#id_alamat").val();
            var no_telpon = $("#id_no_telpon").val();
            var email = $("#id_email").val();
            var jenis_surat = $("#id_jenis_surat").val();
            var keterangan_tambahan = $("#id_keterangan_tambahan").val();
            var str = "<pre>" 
                    + "Nama       : " + nama + "<br>"
                    + "NIK        : " + nik + "<br>"
                    + "Alamat     : " + alamat + "<br>"
                    + "No Tlp.    : " + no_telpon + "<br>"
                    + "Email      : " + email + "<br>"
                    + "Keperluan  : " + jenis_surat + "<br>"
                    + "Keterangan : " + "<div class=\"text-wrap\" style=\"width: 30rem;\">"
                    + keterangan_tambahan + "</div>"
                    + "</pre>"
                    ; 
            $("#modal_body").html(str); 
        }); 
    </script> 
    
</body>
</html>

{% endblock %}

Kependudukan/suket/templates/daftar_borang_masuk.html
{% extends 'layout.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>Daftar Borang Masuk</h4>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Nama</th>
                <th scope="col">NIK</th>
                <th scope="col">Alamat</th>
                <th scope="col">No Telpon</th>
                <th scope="col">Email</th>
                <th scope="col">jenis</th>
                <th scope="col">Keterangan</th>
                <th scope="col" style="width: 10%;">Tindakan</th>
            </tr>
        </thead>
        <tbody>
            {% for dt in data %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ dt.nama }}</td>
                <td>{{ dt.nik }}</td>
                <td>{{ dt.alamat }}</td>
                <td>{{ dt.no_telpon }}</td>
                <td>{{ dt.email }}</td>
                <td>{{ dt.jenis_surat }}</td>
                <td>{{ dt.keterangan_tambahan }}</td>
                <td>
                    <!-- Button untuk trigger modal Hapus -->
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal{{ dt.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </button>
    
                    <!-- Modal hapus -->
                    <div id="myModal{{ dt.id }}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- konten modal-->
                            <div class="modal-content">
                                <!-- heading modal -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Konfirmasi</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <!-- body modal -->
                                <div class="modal-body">
                                    <p>Anda yakin ingin menghapus?</p>
                                </div>
                                <!-- footer modal -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                    <a href="hapus/{{ dt.id }}">  
                                        <button type="button" class="btn btn-danger">Hapus</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Modal hapus -->
    
                    <!-- Button untuk trigger modal cetak -->
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal2{{ dt.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-check-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
                          </svg>
                    </button>
    
                    <!-- Modal cetak -->
                    <div id="myModal2{{ dt.id }}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- konten modal-->
                            <div class="modal-content">
                                <!-- heading modal -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Validasi</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <!-- body modal -->
                                <div class="modal-body">
                                    <p>Data tervalidasi?</p>
                                </div>
                                <!-- footer modal -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                    <a href="pdf/{{ dt.id }}">  
                                        <button type="button" class="btn btn-primary">Konfirmasi</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Modal cetak -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
     
</body>

</html>
{% endblock %}

Kependudukan/suket/templates/konfirmasi.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> 
    <!-- Static css -->
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <title>Cetak</title>
</head>
<body class="A4">
    <!-- Content Body container-->
    <main class="container mt-4">  
        <section class="sheet padding-10mm">
            <table>
                <thead>
                    <tr class="head_row">
                        <td><img class="img_kop" src="{% static 'logo.jpg' %}" alt="logo"></td>
                        <td>
                            <h1>Pemerintah Kabupaten Koding</h1>
                            <h2>Kecamatan Praxis Academy</h2>
                            <h3>Desa Bima Hacker Village</h3>
                            <p class="kop">Jalan Menuju Kesuksesan Bersama-sama Bahagia</p>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <td colspan="2">
                        <p>Pengajuan anda sudah kami terima dan dokumen yang and abutuhkan akan dikirim melalui email yang saudara masukkan.
                            Mohon menunggu selama 3 hari kerja, jika sudah melewati 3 hari kerja, silakan hubungi ke admin</p>
                        <a href="/suket/borang">
                            <button type="button" class="btn btn-success btn-sm">OK</button>
                        </a>
                    </td>
                </tbody>            
            </table>
        </section>
    </main>
    <!-- End Content Body -->
</body>

</html>
{% endblock %}

Kependudukan/suket/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Import bootstrap cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> 
  
    <!-- Import jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"> </script>  
    <script src= "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity= "sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"> </script> 


    <!-- CSS  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> 
    <!-- Static css 
    <link rel="stylesheet" href="{% static 'css.css' %}">
    -->

    <title>Suket</title>
</head>

<body>

  <!-- Block Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(36, 150, 62);;">
    <a class="navbar-brand" href="#">Persuratan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Blog <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Belanja <span class="sr-only">(current)</span></a>
        </li>        
        <li class="nav-item active">
          <a class="nav-link" href="/suket/borang">Suket <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <!-- End Block Navbar -->

  <!-- Content Body -->
  <main class="container-lg mt-4">  
      {% block content %}
      {% endblock %}
  </main>
  <!-- End Content Body -->

  <!-- Javascript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  
  <!-- Static Javascript 
  <link rel="stylesheet" href="{% static 'js.js' %}">
  -->
  

</body>
</html>

Kependudukan/suket/templates/pdf.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> 
    <!-- Static css -->
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <title>Cetak</title>
</head>
<body class="A4">
    <!-- Content Body container-->
    <main class="container mt-4">  
        <section class="sheet padding-10mm">
            <table>
                <thead>
                    <tr class="head_row">
                        <td><img class="img_kop" src="{% static 'logo.jpg' %}" alt=""></td>
                        <td>
                            <h1>Pemerintah Kabupaten Koding</h1>
                            <h2>Kecamatan Praxis Academy</h2>
                            <h3>Desa Bima Hacker Village</h3>
                            <p class="kop">Jalan Menuju Kesuksesan Bersama-sama Bahagia</p>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="SK" colspan="2">
                            Surat keterangan {{ data.jenis_surat }}                            
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-top: 3pt; text-align:center;" colspan="2">
                            <p>NO : ..../..../2021</p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <p>Yang bertanda tangan dibawah ini adalah Kepala Desa Bima Hacker Village,
                                Kecamatan Praxis Academy, Kabupaten Koding menerangkan bahwa:</p>
                        </td>
                    </tr>
                    <div >
                        <tr>
                            <td class="identitas">
                                <p>Nama        </p>
                                <p>NIK         </p>
                                <p>No Telpon   </p>
                                <p>Email       </p>
                                <p>Keperluan   </p>
                                <p>Alamat      </p>
                            </td>
                            <td>
                                <p>: {{ data.nama }}</p>
                                <p>: {{ data.nik }}</p>
                                <p>: {{ data.no_telpon }}</p>
                                <p>: {{ data.email }}</p>
                                <p>: {{ data.jenis_surat }}</p>
                                <p>: {{ data.alamat }}</p>
                            </td>
                        <tr>
                            <td>
                                
                            </td>
                        </tr>
                    </div>
                    <tr>
                        <td colspan="2">
                            <p>Memang benar yang bersangkutan diatas merupakan warga Desa Bima Hacker Village 
                               dan surat ini diberikan kepada yang bersangkutan untuk dipergunakan sebaik-baiknya sesuai kebutuhan.</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            
                        </td>
                        <td>
                            <p style="text-align: end; padding-right: 50pt; line-height: 0.3;">Yogyakarta, {{ date.day }} {{ month }} {{ date.year }} </p>
                            <p style="font-weight: bold; text-align: end; padding-right: 50pt;">Kepala Desa Bima Hacker Village</p>
                            
                            <img style="float: inherit;width: 200px;margin-left: 340pt;" src="{% static 'ttd.png' %}" alt="">
                            
                            <br>
                            <br>
                            <p style="font-weight: bold; text-align: end; padding-right: 50pt; text-decoration: underline; line-height: 0;">Jarene Pak Kades, MM.</p>                                  
                            <p style="font-weight: bold; text-align: end; padding-right: 50pt;"">NIP. 19750203 200005 1 001</p>
                        </td>
                    </tr>

                </tbody>            
            </table>
        </section>
    </main>
    <!-- End Content Body -->
</body>

</html>
{% endblock %}

Kependudukan/templates/index.html
<h1>Ini index</h1>